version: '3.8'
services:
  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGODB_DATABASE: nest-pokemon